### ISSUE TITLE
Blast loading skip by networkin

### ISSUE THREAD

**Issue by aforget2411** [gaelfortin/phosphogo#19]

**Comment by gaelfortin** [comment]
BLASTALL is a requirement for NetworKIN. However NetworKIN ran without any BLAST version installed on the computer when tested. How were NetworKIN outputs?

**Comment by gaelfortin** [comment]
networkin outptus are empty if BLAST is not installed. `run_networkin` should test if BLASTALL is installed before running NetworKIN and send an error
